
# Lets talk Data

### Gathering the Data

There are five data sets that will be used in testing the hypothesis. The focus will be on Japan's GDP to measure its economic state. The remaining four sets include data on Japan's marriages, single-person home rentals, population of elderly 65 and over, and population of youth 15 and under. 

All data used was downloaded from two sources, the links to the datasets can be found below.<br>
<a href="http://data.worldbank.org/indicator/NY.GDP.PCAP.CD?end=2015&locations=JP&start=1960&view=chart">Worldbank</a>: Source for economic data.<br>
<a href="https://knoema.com/urvzrr/japan-regional-dataset-may-2015?tsId=1063510">Knoema</a>: Source of marriages, single-person hoem rentals, and population data.

### Cleaning the Data

All five sources of data used are in a format that has more than what is needed for this hypothesis. The data corresponding to the GDP shows information about all countries versus that of just Japan. It also has elements which are unnecessary need including "Country Code", "Indicator Name", and "Indicator Code". The data taken from Knoema shows information for each region of Japan instead of the country as a whole. It is also formatted such that each region has its own row per year

In [20]:
import csv
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# Data files
marriageDataFile = "Marriages.csv"
singleHomeDataFile = "One-Person_Household.csv"
gdpDataFile = "GDP.csv"
under15DataFile = "Pop15Under.csv"
over65DataFile = "Pop65Older.csv"

# Import Data Files
marriageData = pd.read_csv(marriageDataFile)
singleHomeData = pd.read_csv(singleHomeDataFile)
gdpData = pd.read_csv(gdpDataFile)
under15Data = pd.read_csv(under15DataFile)
over65Data = pd.read_csv(over65DataFile)

#marriageData
singleHomeData
#under15Data
#over65Data
#gdpData

     ï»¿"region"              indicator    Unit  Date   Value
0      Saitama  One-person households  Number  1975  136194
1      Saitama  One-person households  Number  1980  184873
2      Saitama  One-person households  Number  1985  286840
3      Saitama  One-person households  Number  1990  398507
4      Saitama  One-person households  Number  1995  488804
5      Saitama  One-person households  Number  2000  571905
6      Saitama  One-person households  Number  2005  662642
7      Saitama  One-person households  Number  2010  806579
8        Aichi  One-person households  Number  1975  186813
9        Aichi  One-person households  Number  1980  238983
10       Aichi  One-person households  Number  1985  410927
11       Aichi  One-person households  Number  1990  504553
12       Aichi  One-person households  Number  1995  589585
13       Aichi  One-person households  Number  2000  661805
14       Aichi  One-person households  Number  2005  783157
15       Aichi  One-person households  Number  2010  923424
16       Akita  One-person households  Number  1975   25354
17       Akita  One-person households  Number  1980   34030
18       Akita  One-person households  Number  1985   48831
19       Akita  One-person households  Number  1990   57006
20       Akita  One-person households  Number  1995   69664
21       Akita  One-person households  Number  2000   82502
22       Akita  One-person households  Number  2005   89027
23       Akita  One-person households  Number  2010   95609
24      Aomori  One-person households  Number  1975   38393
25      Aomori  One-person households  Number  1980   53739
26      Aomori  One-person households  Number  1985   75134
27      Aomori  One-person households  Number  1990   85074
28      Aomori  One-person households  Number  1995  105200
29      Aomori  One-person households  Number  2000  121473
..         ...                    ...     ...   ...     ...
346   Wakayama  One-person households  Number  1985   53795
347   Wakayama  One-person households  Number  1990   60930
348   Wakayama  One-person households  Number  1995   73341
349   Wakayama  One-person households  Number  2000   83448
350   Wakayama  One-person households  Number  2005   90736
351   Wakayama  One-person households  Number  2010  107692
352   Yamagata  One-person households  Number  1975   21375
353   Yamagata  One-person households  Number  1980   29616
354   Yamagata  One-person households  Number  1985   42065
355   Yamagata  One-person households  Number  1990   49787
356   Yamagata  One-person households  Number  1995   63077
357   Yamagata  One-person households  Number  2000   75169
358   Yamagata  One-person households  Number  2005   84043
359   Yamagata  One-person households  Number  2010   89817
360  Yamaguchi  One-person households  Number  1975   55602
361  Yamaguchi  One-person households  Number  1980   69852
362  Yamaguchi  One-person households  Number  1985  100033
363  Yamaguchi  One-person households  Number  1990  115202
364  Yamaguchi  One-person households  Number  1995  137954
365  Yamaguchi  One-person households  Number  2000  155809
366  Yamaguchi  One-person households  Number  2005  166468
367  Yamaguchi  One-person households  Number  2010  182632
368  Yamanashi  One-person households  Number  1975   22410
369  Yamanashi  One-person households  Number  1980   28494
370  Yamanashi  One-person households  Number  1985   40875
371  Yamanashi  One-person households  Number  1990   49768
372  Yamanashi  One-person households  Number  1995   65425
373  Yamanashi  One-person households  Number  2000   74413
374  Yamanashi  One-person households  Number  2005   82843
375  Yamanashi  One-person households  Number  2010   90064

[376 rows x 5 columns]